#Versi API yang digunakan
apiVersion: apps/v1

#Nama Jenis objek Deployment
kind: Deployment

#Metadata ini berisi informasi tambahan tentang objek seperti nama dan label
metadata:
  name: karsajobs-ui-deployment

spec:
  replicas: 3  #Menentukan jumlah replika yang akan dijalankan
  selector:
    matchLabels: #label karsajobs-ui yang akan terhubung dengan service
      app: karsajobs-ui

  template: #template pod untuk menentukan label 
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs-ui:latest
          ports:
            - containerPort: 80  #Port yang digunakan oleh kontainer
