#versi docker
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine #image yang digunakan
    container_name: rabbitmqserv #nama kontainer rabbitmq
    ports: #konfigurasi port pada rabbitmq
      - 5672:5672
      - 15672:15672
    volumes: #Volume-volume ini digunakan untuk mengatur penyimpanan data dan log untuk kontainer RabbitMQ
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks: #konfigurasi network untuk rabbitmq
      - rabbitmq_network

  order-service: #bagian order-service
    image: ghcr.io/amrilhakimsihotang/a433-microservices/order-service:v1 #image yang digunakan
    container_name: orderservice #nama kontainer untuk image order-service
    depends_on: #menjalankan terlebih dahulu service rabbitmq
      - rabbitmq
    ports: #konfigurasi port pada order-service
      - 3000:3000
    #untuk menunggu ketersediaan layanan RabbitMQ di host dan port yang ditentukan (rabbitmq:5672)
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    environment: #pengaturan untuk lingkungan env
      - PORT=3000 #port yang digunakan order-service
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672 #protokol amqp untuk mengakses RabbitMQ dengan kredensial user guest

    networks: #konfigurasi network untuk order-service
      - rabbitmq_network

  shipping-service:
    image: ghcr.io/amrilhakimsihotang/a433-microservices/shipping-service:v1 #image yang digunakan
    container_name: shippingservice #nama kontainer untuk image shipping-service
    depends_on: #menjalankan terlebih dahulu service rabbitmq
      - rabbitmq
    ports: #konfigurasi port pada order-service
      - 3001:3001
    #untuk menunggu ketersediaan layanan RabbitMQ di host dan port yang ditentukan (rabbitmq:5672)
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=50 -- node index.js'
    environment:
      - PORT=3001 #port yang digunakan shipping-service
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672 #protokol amqp untuk mengakses RabbitMQ dengan kredensial user guest

    networks: #konfigurasi network untuk order-service
      - rabbitmq_network

networks: #type network yang digunakan bridge
  rabbitmq_network:
    driver: bridge
