version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      - run:
          name: Lint Dockerfile
          command: |
            wget https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
            mv hadolint-Linux-x86_64 hadolint
            chmod +x hadolint
            ./hadolint Dockerfile

      - run:
          name: Test Backend
          command: go test -v -short --count=1 $(go list ./...)

      - run:
          name: Build and Push Image
          command: |
            docker build -t ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs:latest .
            echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
            docker push ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            branches:
              only: karsajobs
