version: 2.1

environment:
      # Konfigurasi
      GITHUB_TOKEN="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"
jobs:
  lint-dockerfile:
    docker: #Menggunakan image Docker circleci/golang:1.16
      - image: circleci/golang:1.16
    steps:
      - checkout

      #Download dan install hadolint
      - run:
          name: Install hadolint
          command: |
            wget https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
            chmod +x hadolint-Linux-x86_64
            sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint

      #Jalankan hadolint  Dockerfile
      - run:
          name: Run hadolint
          command: hadolint Dockerfile

  test-app: 
    docker: #Menggunakan image Docker circleci/golang:1.16
      - image: circleci/golang:1.16

    steps:
      - checkout

      #Jalankan unit tests for backend
      - run:
          name: Run unit tests
          command: go test -v -short --count=1 $(go list ./...)
  
  build-app-karsajobs:
    docker:
    - image: circleci/golang:1.16
    steps:
      - checkout
      - setup_remote_docker
      # Build and push image
      - run:
         name: "Build Image"
         command: docker build -t karsajobs:latest .
      
      - run:
         name: "Rename Image"
         command: docker tag karsajobs:latest ghcr.io/amrilhakimsihotang/a433-microservices/karsajobs:latest

      - run:
         name: "Login"
         command: echo $GITHUB_ACCESS_TOKEN | docker login ghcr.io -u amrilhakimsihotang --password-stdin      
      
      - run:
         name: "push image ke github registry"
         command: docker push ghcr.io/amrilhakimsihotang/a433-microservices/karsajobs:latest


workflows:
  version: 2.1
  lint-test-build-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
