version: 2.1 # Menentukan versi Github Action yang digunakan

jobs:
  build:
    docker: # Menggunakan container Docker dengan image golang
    - image: golang:1.15-alpine

    steps: # Langkah-langkah yang akan dieksekusi
    - checkout

    - run:
        name: Lint Dockerfile
        command: |
          apk --no-cache add curl
          curl -sL https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64 > hadolint
          chmod +x hadolint
          ./hadolint Dockerfile

    - run:
        name: Test App
        command: go test -v -short --count=1 $(go list ./...)

    - run:
        name: Build and Push App Image
        # Build and push Docker image ke GitHub registry
        command: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${GITHUB_USERNAME}" --password-stdin
          docker build -t ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs:latest .
          docker push ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs:latest

workflows: # Mendefinisikan workflow 
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            only:
            - karsajobs
