environment:
      # Konfigurasi
      GITHUB_USERNAME="amrilhakimsihotang"
      GITHUB_TOKEN="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"
      IMAGE_NAME="amril2023/karsajobs"
      IMAGE_TAG="latest"
      REPOSITORY="a433-microservices"
version: 2.1

jobs:
  lint-dockerfile:
    docker: #Menggunakan image Docker circleci/golang:1.16
      - image: circleci/golang:1.16
    steps:
      - checkout

      #Download dan install hadolint
      - run:
          name: Install hadolint
          command: |
            wget https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
            chmod +x hadolint-Linux-x86_64
            sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint

      #Jalankan hadolint  Dockerfile
      - run:
          name: Run hadolint
          command: hadolint Dockerfile

  test-app: 
    docker: #Menggunakan image Docker circleci/golang:1.16
      - image: circleci/golang:1.16

    steps:
      - checkout

      #Jalankan unit tests for backend
      - run:
          name: Run unit tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout

      # Build and push image
      - run:
          name: Build and push image
          command: |
            #1. Perintah build docker image untuk backend
            echo "Membuat Docker image..."

            docker build -t ghcr.io/$IMAGE_NAME:${CIRCLE_SHA1} . 

            # Tagging image untuk GitHub Container Registry..
            echo "Tagging Docker image untuk GitHub Container Registry..."
            docker tag $IMAGE_NAME:${CIRCLE_SHA1} ghcr.io/$GITHUB_USERNAME/$REPOSITORY/$IMAGE_NAME:${CIRCLE_SHA1}

            #2.Login ke GitHub Container Registry(menerapkan saran kedua)
            echo "Masuk ke GitHub Container Registry..."
            echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin

            #3.Push image ke GitHub Container Registry(menerapkan saran kedua)
            echo "Push image ke GitHub Container Registry..."
            docker push ghcr.io/$GITHUB_USERNAME/$REPOSITORY/$IMAGE_NAME:${CIRCLE_SHA1}

            # Logout dari GitHub Container Registry
            echo "Logout dari GitHub Container Registry..."
            docker logout ghcr.io

            # Image upload selesai
            echo "Image upload selesai!"
workflows:
  version: 2.1
  lint-test-build-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
