version: 2.1 # Menentukan versi Github Action yang digunakan

jobs: # Mendefinisikan Jobs yang akan dilakukan
  lint-dockerfile:
    docker: # Menggunakan container Docker dengan image hadolint/hadolint:latest
    - image: hadolint/hadolint:latest
    steps: # Langkah-langkah yang akan dieksekusi
    - checkout
    - run:
        name: Lint Dockerfile
        command: hadolint Dockerfile

  test-app: # Job untuk menjalankan unit tests pada aplikasi Go
    docker: # Menggunakan container Docker dengan image golang:latest
    - image: golang:latest
    steps: # Langkah-langkah yang akan dieksekusi
    - checkout
    - run:
        name: Run Unit Tests
        command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker: # Menggunakan container Docker dengan image golang:latest.
    - image: golang:latest
    steps: # Langkah-langkah yang akan dieksekusi
    - checkout
    - run:
        name: Build and Push Docker Image
        command: |
          # Build and push Docker image ke GitHub registry
          echo "$GITHUB_TOKEN" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
          docker build -t ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs-ui:latest .
          docker push ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs-ui:latest


workflows: # Mendefinisikan workflow 
  version: 2
  lint-test-and-deploy: # Workflow yang menjalankan job secara berurutan.
    jobs:
    - lint-dockerfile # Job pertama yang akan dieksekusi
    - test-app: # Job kedua selanjutnya dieksekusi
        requires:
        - lint-dockerfile
    - build-app-karsajobs: #  Yang membutuhkan successful completion dari job sebelumnya.
        requires:
        - test-app
