version: 2.1 # Menentukan versi Github Action yang digunakan

jobs: # Mendefinisikan Jobs yang akan dilakukan
  lint-dockerfile: #1
    docker:
    - image: python:latest #image yang digunakan
    steps:
    - checkout
    - run:
        name: Lint Dockerfile
        command: |
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 &&
          chmod +x /bin/hadolint &&
          hadolint Dockerfile

  build-app-karsajobs-ui: #2 Build app karsajobs-ui
    docker:
    - image: cimg/base:current #Image docker yang digunakan
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true #mengaktifkan docker_layer_caching
    - run:
        name: Login to Docker GITHUB #login ke Github
        command: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin

      # - run:
    - run:
        name: Build and Push Docker Image # Build and push Docker image ke GitHub registry
        command: "sudo mkdir /build && \ndocker build -t ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs-ui:latest . &&\ndocker push ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs-ui:latest\n#magic___^_^___line\n"
workflows: # Mendefinisikan workflow 
  version: 2
  karsajobs-ui:
    jobs: #Job yang dilakukan untuk branch karsajob-ui
    - lint-dockerfile:
        filters:
          branches:
            only: karsajobs-ui

    - build-app-karsajobs-ui:
        filters:
          branches:
            only: karsajobs-ui
