version: 2.1 # Menentukan versi Github Action yang digunakan

jobs:
  build:
    docker: # Menggunakan container Docker dengan image golang
    - image: golang:1.15-alpine

    steps: # Langkah-langkah yang akan dieksekusi
    - checkout

    - run:
        name: Lint Dockerfile # Define the name of the step
        command: |
          apk --no-cache add curl
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 &&\
          chmod +x /bin/hadolint

    - run:
        name: Install build dependencies # Menginstal build dependensi 
        command: |
          apk --no-cache add build-base

    - run:
        name: Install Docker
        command: |
          apk --no-cache add docker
          rc-service docker start
          docker info

    - run:
        name: Test App
        command: go test -v -short --count=1 $(go list ./...)

    - run:
        name: Build and Push App Image
        # Build and push Docker image ke GitHub registry
        command: |
          # Build and push Docker image ke GitHub registry
          echo "$GITHUB_TOKEN" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
          docker build -t ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs:latest .
          docker push ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs:latest

workflows: # Mendefinisikan workflow 
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            only:
            - karsajobs
