version: 2.1 # Menentukan versi Github Action yang digunakan

jobs:
  build:
    docker: # Menggunakan container Docker dengan image golang
    - image: golang:1.15-alpine

    steps: # Langkah-langkah yang akan dieksekusi
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint Dockerfile
      run: |
        apk --no-cache add curl
        wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 &&\
        chmod +x /bin/hadolint

    - name: Install build dependencies
      run: |
        apk --no-cache add build-base

    - name: Install Docker
      run: |
        apk --no-cache add docker

    - name: Test App
      run: go test -v -short --count=1 $(go list ./...)

    - name: Build and Push App Image # Build and push Docker image ke GitHub registry
      run: |
        cd "${GITHUB_WORKSPACE}/karsajobs" || exit
        sh build_push_image_karsajobs.sh

workflows: # Mendefinisikan workflow 
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            only:
            - karsajobs
